version: '3.4'

services:
  # DB related stuff
  novarecipesproject_postgresql:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "5432:5432"
    networks:
      - shared_novarecipesproject_net
    volumes:
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

# Solution WEBAPI projects
  novarecipesproject_api:
    ports:
      - "10000:80"
    networks:
      - shared_novarecipesproject_net
    env_file:
      - env.api
      
  novarecipesproject_identity:
    ports:
      - "10001:80"
    networks:
      - shared_novarecipesproject_net
    env_file:
      - env.identity

  novarecipesproject_emailsenderworker_1:
    networks:
      - shared_novarecipesproject_net
    env_file:
      - env.emailsenderworker

  novarecipesproject_emailsenderworker_2:
    networks:
      - shared_novarecipesproject_net
    env_file:
      - env.emailsenderworker

  novarecipesproject_recipeinfosenderworker_1:
    networks:
      - shared_novarecipesproject_net
    env_file:
      - env.recipeinfosenderworker

  novarecipesproject_recipeinfosenderworker_2:
    networks:
      - shared_novarecipesproject_net
    env_file:
      - env.recipeinfosenderworker

  novarecipesproject_newcommentssenderworker_1:
    networks:
      - shared_novarecipesproject_net
    env_file:
      - env.newcommentsenderworker

  novarecipesproject_newcommentssenderworker_2:
    networks:
      - shared_novarecipesproject_net
    env_file:
      - env.newcommentsenderworker

# Misc services
  # Redis
  novarecipesproject_redis:
    ports:
      - "6379:6379"
    networks:
      - shared_novarecipesproject_net
    volumes:
      - ~/.docker-conf/redis/data/:/data    
  # RabbitMQ
  novarecipesproject_rabbitmq:
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672"
    networks:
      - shared_novarecipesproject_net
    volumes:
      - ./.rabbitmq:/var/lib/rabbitmq

# Other configuration
networks:
  shared_novarecipesproject_net:
    name: novarecipesproject
    driver: bridge
