version: '3.4'

services:

# Database
  novarecipesproject_postgresql:
    image: postgres:14.1

# Misc services
  # Redis
  novarecipesproject_redis:
    image: redis
  # RabbitMQ
  novarecipesproject_rabbitmq:
    image: rabbitmq:management

# Solution WEBAPI projects
  novarecipesproject_api:
    image: ${DOCKER_REGISTRY-}novarecipesprojectapi
    build:
      context: .
      dockerfile: Systems/Api/NovaRecipesProject.Api/Dockerfile
    depends_on:
      - novarecipesproject_postgresql
      - novarecipesproject_redis

  novarecipesproject_identity:
    image: ${DOCKER_REGISTRY-}novarecipesprojectidentity
    build:
      context: .
      dockerfile: Systems/Identity/NovaRecipesProject.Identity/Dockerfile
    depends_on:
      - novarecipesproject_postgresql
      - novarecipesproject_redis
      - novarecipesproject_api

  #novarecipesproject_commentsmailingjobscheduler:
  #  image: ${DOCKER_REGISTRY-}novarecipesprojectcommentsmailingjobscheduler
  #  build:
  #    context: .
  #    dockerfile: Systems/Schedulers/NovaRecipesProject.CommentsMailingJobScheduler/Dockerfile
  #  depends_on:
  #    - novarecipesproject_postgresql
  #    - novarecipesproject_redis
  #    - novarecipesproject_rabbitmq
  #    - novarecipesproject_api

  novarecipesproject_recipeinfosenderworker_1:
    image: ${DOCKER_REGISTRY-}novarecipesprojectrecipeinfosenderworker
    build:
      context: .
      dockerfile: Systems/Workers/NovaRecipesProject.RecipeInfoSenderWorker/Dockerfile
    depends_on:
      - novarecipesproject_postgresql
      - novarecipesproject_redis
      - novarecipesproject_rabbitmq
      - novarecipesproject_api

  novarecipesproject_recipeinfosenderworker_2:
    image: ${DOCKER_REGISTRY-}novarecipesprojectrecipeinfosenderworker
    build:
      context: .
      dockerfile: Systems/Workers/NovaRecipesProject.RecipeInfoSenderWorker/Dockerfile
    depends_on:
      - novarecipesproject_postgresql
      - novarecipesproject_redis
      - novarecipesproject_rabbitmq
      - novarecipesproject_api

  novarecipesproject_emailsenderworker_1:
    image: ${DOCKER_REGISTRY-}novarecipesprojectemailsenderworker
    build:
      context: .
      dockerfile: Systems/Workers/NovaRecipesProject.EmailSenderWorker/Dockerfile
    depends_on:
      - novarecipesproject_postgresql
      - novarecipesproject_redis
      - novarecipesproject_rabbitmq
      - novarecipesproject_api

  novarecipesproject_emailsenderworker_2:
    image: ${DOCKER_REGISTRY-}novarecipesprojectemailsenderworker
    build:
      context: .
      dockerfile: Systems/Workers/NovaRecipesProject.EmailSenderWorker/Dockerfile
    depends_on:
      - novarecipesproject_postgresql
      - novarecipesproject_redis
      - novarecipesproject_rabbitmq
      - novarecipesproject_api

  novarecipesproject_newcommentssenderworker_1:
    image: ${DOCKER_REGISTRY-}novarecipesprojectnewcommentssenderworker
    build:
      context: .
      dockerfile: Systems/Workers/NovaRecipesProject.RecipeNewCommentsSenderWorker/Dockerfile
    depends_on:
      - novarecipesproject_postgresql
      - novarecipesproject_redis
      - novarecipesproject_rabbitmq
      - novarecipesproject_api

  novarecipesproject_newcommentssenderworker_2:
    image: ${DOCKER_REGISTRY-}novarecipesprojectnewcommentssenderworker
    build:
      context: .
      dockerfile: Systems/Workers/NovaRecipesProject.RecipeNewCommentsSenderWorker/Dockerfile
    depends_on:
      - novarecipesproject_postgresql
      - novarecipesproject_redis
      - novarecipesproject_rabbitmq
      - novarecipesproject_api