version: '3.4'

services:
  # DB related stuff
  novarecipesproject_postgresql:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "5432:5432"
    networks:
      - shared_novarecipesproject_net
    volumes:
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

# Solution WEBAPI projects
  novarecipesproject_api:
    ports:
      - "10000:80"
    networks:
      - shared_novarecipesproject_net
    env_file:
      - env.api
      
  novarecipesproject_identity:
    ports:
      - "10001:80"
    networks:
      - shared_novarecipesproject_net
    env_file:
      - env.identity

# Misc services
  novarecipesproject_redis:
    ports:
      - "6379:6379"
    networks:
      - shared_novarecipesproject_net
    volumes:
      - ~/.docker-conf/redis/data/:/data    

# Other configuration
networks:
  shared_novarecipesproject_net:
    name: novarecipesproject
    driver: bridge